//SECURITY
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//PRODUCT
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_PRODUCTS_BY_SUPPLIER = "GET_PRODUCTS_BY_SUPPLIER";

//CATEGORY
export const ADD_CATEGORY = "ADD_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";

//SUPPLIER
export const ADD_SUPPLIER = "ADD_SUPLIER";
export const ADD_SUPPLIER_CONTACT = "ADD_SUPPLIER_CONTACT";
export const ADD_SUPPLIER_BANK_ACCOUNT = "ADD_SUPPLIER_BANK_ACCOUNT";
export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const GET_SUPPLIER = "GET_SUPPLIER";
export const GET_SUPPLIER_CONTACT = "GET_SUPPLIER_CONTACT";
export const GET_SUPPLIER_CONTACTS = "GET_SUPPLIER_CONTACTS";
export const GET_SUPPLIER_BANK_ACCOUNT = "GET_SUPPLIER_BANK_ACCOUNT";
export const GET_SUPPLIER_BANK_ACCOUNTS = "GET_SUPPLIER_BANK_ACCOUNT";
export const DELETE_SUPPLIER = "DELETE_SUPPLIER";
export const DELETE_SUPPLIER_BANK_ACCOUNT = "DELETE_SUPPLIER_BANK_ACCOUNT";

//CART
export const SEARCH_ITEMS = "SEARCH_ITEMS";
export const GET_CART = "GET_CART";
export const ADD_CART = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_CART";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const SUB_QUANTITY = "SUB_QUANTITY";
export const RESET_CART = "RESET_CART";

//STOCK
export const GET_WAREHOUSES = "GET_WAREHOUSES";
export const GET_WAREHOUSE = "GET_WAREHOUSE";
export const GET_STOCK = "GET_STOCK";

//ERRORS
export const GET_ERRORS = "GET_ERRORS";